name: Question
description: Ask a question about the core application.
labels: ["needs-triage", "question"]
body:
  - type: "textarea"
    attributes:
      label: "What is your question?"
      description: "A clear and concise question."
      placeholder: "How do I [...]. Is there a way to [...]? "
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for asking a question! We will get back to you as soon as possible.
